In [43]:
from sklearn.datasets import load_diabetes
#from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import pandas as pd
import joblib
import os

In [44]:
#Pre-processing-convert categorical features




# Split the dataframe into test and train data
def split_data(df):
    X = df.drop('target_rP', axis=1).values
    y = df['target_rP'].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=0)
    data = {"train": {"X": X_train, "y": y_train},
            "test": {"X": X_test, "y": y_test}}
    return data


# Train the model, return the model
def train_model(data, args):
    rf_model = RandomForestClassifier(**args)
    rf_model.fit(data["train"]["X"], data["train"]["y"])
    return rf_model


# Evaluate the metrics for the model
def get_model_metrics(rf_model, data):
    preds = rf_model.predict(data["test"]["X"])
    accuracy = balanced_accuracy_score(preds, data["test"]["y"])
    metrics = {"accuracy": accuracy}
    return metrics


# def main():
#     # Load Data
#     sample_data = load_diabetes()

#     # Load the training data as dataframe
#     data_dir = "../data"
    
#     data_file = os.path.join(data_dir, 'training_data.csv')
    
#     train_df = pd.read_csv(data_file)

#     # Split Data into Training and Validation Sets
#     data = split_data(df)

#     # Train Model on Training Set
#     args = {
#         "alpha": 0.5
#     }
#     reg = train_model(data, args)

#     # Validate Model on Validation Set
#     metrics = get_model_metrics(reg, data)

#     # Save Model
#     model_name = "sklearn_regression_model.pkl"

#     joblib.dump(value=reg, filename=model_name)

# if __name__ == '__main__':
#     main()

In [4]:
data_dir = "../data"

data_file = os.path.join(data_dir, 'training_data.csv')

train_df = pd.read_csv(data_file)

In [5]:
train_df.columns

Index(['id_2017J', 'course', 'pres5', 'credits', 'level', 'best_mod_score',
       'ave_mods_score', 'pctcred_pa_reach_pct25', 'pctcred_pa_reach_pct50',
       'pctcred_pa_reach_pct100', 'pctcred_pa_reach_rC', 'pctcred_pa_reach_rP',
       'pct_pa_pass', 'pct_pa_fail', 'comp_rate_mod_higher_lev',
       'yr_since_last_rr1', 'main_pay_type', 'qual_linked',
       'creds_pass_or_transf_to_award', 'award_progress',
       'module_rP_qual_lastyr', 'same_mod_lastyr_reg',
       'pct_tma1_due_subm_lastyr', 'module_pa_cur_pres',
       'sum_pa_credits_cur_pres', 'sum_exam_cur_pres', 'is_over_120_cur_pres',
       'price_a', 'new_cont', 'hiedlev', 'occstatus', 'IMD_prop',
       'segment_2013', 'pris_type', 'is_late_reg_plus_7', 'hesa_disable',
       'Slc_loan_module', 'spons_module', 'target_rr1', 'target_25pct',
       'target_50pct', 'target_100pct', 'target_rC', 'target_rP',
       'target_rPir', 'target_module_tma1_subm', 'level_lastmod',
       'module_score_lastmod', 'module_result_lastmod', 'score_tma1_lastmod',
       'hesa_courseaim_level', 'cau', 'course_length', 'lead_programme_id',
       'pres_number_tma_equivs', 'mod_hesa_group', 'mod_hesa_group_code2',
       'mod_examinable_component2', 'sca_module',
       'iopm_vle_vis_day_start_to_pct25', 'degree_with_hons'],
      dtype='object')

In [8]:
train_df1 = train_df[['comp_rate_mod_higher_lev', 'hesa_courseaim_level', 'hesa_disable', 'level_lastmod',
                     'module_result_lastmod', 'pctcred_pa_reach_pct100', 'pctcred_pa_reach_rC', 'pctcred_pa_reach_rP',
                     'Slc_loan_module', 'award_progress', 'iopm_vle_vis_day_start_to_pct25', 'level',
                     'mod_examinable_component2', 'module_rP_qual_lastyr', 'qual_linked', 'same_mod_lastyr_reg',
                     'segment_2013', 'target_rP']]

In [20]:
train_df1.to_csv('../data/student_data.csv', index = False)

In [54]:
data_dir = "../data"

data_file = os.path.join(data_dir, 'student_data.csv')

train_df = pd.read_csv(data_file)

In [55]:
train_df.head()

,comp_rate_mod_higher_lev,hesa_courseaim_level,hesa_disable,level_lastmod,module_result_lastmod,pctcred_pa_reach_pct100,pctcred_pa_reach_rC,pctcred_pa_reach_rP,Slc_loan_module,award_progress,iopm_vle_vis_day_start_to_pct25,level,mod_examinable_component2,module_rP_qual_lastyr,qual_linked,same_mod_lastyr_reg,segment_2013,target_rP
0,1.000000,H,57.0,1,1,1.000000,1.000000,1.000000,0,first_quarter,0.769231,1,Exam,2,Q36,0,PC,1
1,1.000000,H,57.0,1,1,1.000000,1.000000,1.000000,0,first_quarter,0.846154,1,Exam,2,Q36,0,PC,1
2,0.111111,H,0.0,3,W,0.596154,0.115385,0.115385,0,first_quarter,0.076923,2,Other,0,BD,0,Unk,1
3,1.000000,C,0.0,1,1,1.000000,1.000000,1.000000,0,no_award_progress,0.384615,1,Exam,1,icu,0,PC,1
4,1.000000,H,0.0,3,2,1.000000,0.538462,0.538462,0,no_award_progress,1.384615,3,Other,0,icu,0,PC,0

In [56]:
#pre-processing - convert categorical columns into label encoding
category_columns = train_df.select_dtypes(include=['object']).columns
for column in category_columns:
    train_df[column] = train_df[column].astype('category')
    train_df[column] = train_df[column].cat.codes

train_df = train_df.fillna(train_df.mode())

In [57]:
category_columns

Index(['hesa_courseaim_level', 'level_lastmod', 'module_result_lastmod',
       'award_progress', 'mod_examinable_component2', 'qual_linked',
       'segment_2013'],
      dtype='object')

In [58]:
train_df.head(20)

,comp_rate_mod_higher_lev,hesa_courseaim_level,hesa_disable,level_lastmod,module_result_lastmod,pctcred_pa_reach_pct100,pctcred_pa_reach_rC,pctcred_pa_reach_rP,Slc_loan_module,award_progress,iopm_vle_vis_day_start_to_pct25,level,mod_examinable_component2,module_rP_qual_lastyr,qual_linked,same_mod_lastyr_reg,segment_2013,target_rP
0,1.000000,1,57.0,1,0,1.000000,1.000000,1.000000,0,2,0.769231,1,0,2,66,0,9,1
1,1.000000,1,57.0,1,0,1.000000,1.000000,1.000000,0,2,0.846154,1,0,2,66,0,9,1
2,0.111111,1,0.0,3,14,0.596154,0.115385,0.115385,0,2,0.076923,2,2,0,36,0,10,1
3,1.000000,0,0.0,1,0,1.000000,1.000000,1.000000,0,4,0.384615,1,0,1,254,0,9,1
4,1.000000,1,0.0,3,1,1.000000,0.538462,0.538462,0,4,1.384615,3,2,0,254,0,9,0
5,1.000000,2,0.0,2,4,1.000000,0.428571,0.428571,0,4,0.076923,3,2,0,254,0,9,0
6,0.800000,1,0.0,3,2,0.857143,0.714286,0.714286,0,4,2.000000,2,0,0,101,0,9,1
7,1.000000,1,57.0,1,3,1.000000,1.000000,1.000000,0,4,1.230769,1,0,0,85,0,9,1
8,0.875000,2,0.0,2,12,0.925926,0.805556,0.694444,0,4,0.384615,2,2,0,254,0,10,0
9,1.000000,0,0.0,4,11,1.000000,1.000000,1.000000,0,4,1.076923,1,1,0,254,0,9,1
10,1.000000,1,0.0,3,1,1.000000,1.000000,0.800000,1,3,0.461538,3,2,1,36,0,9,1
11,NaN,1,0.0,2,0,1.000000,1.000000,1.000000,1,5,1.461538,3,2,1,87,0,1,1
12,0.000000,1,8.0,3,14,0.875000,0.375000,0.375000,0,4,0.307692,3,2,0,254,0,2,0
13,1.000000,1,0.0,3,3,0.625000,0.625000,0.625000,0,2,1.307692,3,2,1,120,0,5,1
14,0.500000,1,0.0,2,4,1.000000,0.600000,0.600000,1,2,0.000000,2,2,1,97,1,1,1
15,NaN,1,0.0,2,3,1.000000,1.000000,1.000000,1,1,0.307692,3,0,2,65,0,5,1
16,1.000000,1,0.0,2,2,0.750000,0.750000,0.750000,1,5,0.076923,2,0,1,119,0,5,1
17,0.333333,1,55.0,2,2,0.647059,0.558824,0.558824,1,2,0.846154,2,2,1,120,0,1,0
18,NaN,1,55.0,2,3,0.866667,0.733333,0.533333,1,5,0.000000,3,0,2,56,0,1,0
19,NaN,1,55.0,2,3,0.866667,0.733333,0.533333,1,5,0.000000,3,0,2,56,0,1,0

In [36]:
train_df.target_rP.value_counts()

1    61552
0    29062
Name: target_rP, dtype: int64

In [37]:
# Split Data into Training and Validation Sets
data = split_data(train_df)

In [45]:
# Train Model on Training Set
args = {
    "max_depth": 8,
    "n_estimators":50
}

rf_cls = train_model(data, args)

#Validate Model on Validation Set
metrics = get_model_metrics(rf_cls, data)

for (k, v) in metrics.items():
    print(f"{k}: {v}")

accuracy: 0.7112036112220869

In [50]:
data['train']['X'][0]

array([ 1.        ,  1.        ,  0.        ,  2.        ,  2.        ,
        1.        ,  1.        ,  1.        ,  0.        ,  5.        ,
        0.84615385,  2.        ,  0.        ,  1.        , 54.        ,
        0.        ,  2.        ])

In [52]:
data['train']['y'][0]

1

In [ ]:
X_train = np.array([1.        ,  1.        ,  0.        ,  2.        ,  2.        ,
        1.        ,  1.        ,  1.        ,  0.        ,  5.        ,
        0.84615385,  2.        ,  0.        ,  1.        , 54.        ,
        0.        ,  2.]).reshape(-1, 1)
y_train = np.array([10, 9, 8, 8, 6, 5])
data = {"train": {"X": X_train, "y": y_train}}

reg_model = train_model(data, {"alpha": 1.2})

preds = reg_model.predict([[1], [2]])
np.testing.assert_almost_equal(preds, [9.93939393939394, 9.03030303030303])